### PR TITLE
Add Shiro Casdoor to Shiro integrations

### PR DESCRIPTION
**Pull request by seriouszyx**
Hi! Thank you so much for developing such a good and useful application security framework. I'm a developer from [Casdoor](https://casdoor.org/), which is a UI-first centralized authentication / Single-Sign-On (SSO) platform supporting OAuth 2.0, OIDC and SAML.

We developed a plugin [shiro-casdoor](https://github.com/casdoor/shiro-casdoor) to make the integration of Casdoor and Shiro easier. And we also provided the [casdoor-spring-boot-shiro-example](https://github.com/casdoor/casdoor-spring-boot-shiro-example) to illustrate how to use Shiro and Casdoor in a Spring Boot application with this plugin.

We hope shiro-casdoor can be added to the Shiro integrations docs. If you have any questions, welcome to discuss them with me!

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@bdemers @bmarwell plz review

**Review by bdemers — APPROVED** [review]

**Comment by seriouszyx** [comment]
@bdemers Hi, is this PR ready to be merged? Or some more information I should provide?

**Comment by bdemers** [comment]
Looks good!

**Comment by hsluoyz** [comment]
Hi @bdemers , why is this PR still not effective in: https://shiro.apache.org/integration.html ? Is there anything else we need to do?

**Comment by bmarwell** [comment]
Yes, we need to build the site. This will be done with the next version 1.9.0, which is expected in the middle of this month (2022 March).

**Pull request merged**
