### PR TITLE
Add Realm Authorization section

### PR DESCRIPTION
**Pull request by singhkgautam**
Added Realm Authorization section. Please review

### CODE REVIEW

**Comment by bdemers** [comment]
Cool! I'll take a closer look and get it deployed this week

**Comment by gksinghiet** [comment]
Brian, did you get a chance to look into this change?

**Comment by bdemers** [comment]
Sorry, I've been a bit slammed.  I'll block out some time early next week to merge a handful of PRs

**Comment by bdemers** [comment]
Merged! Thanks!!

**Pull request closed without merging**
