### PR TITLE
Update realm.md.vtl

### PR DESCRIPTION
**Pull request by Amitsharma0201**

### CODE REVIEW

**Review by fpapon — APPROVED** [review]
Good catch!
LGTM

**Comment by Nek-** [comment]
@fpapon this user is known as spammer for hacktoberfest. Please add the label `spam` to this PR.

Learn more: https://hacktoberfest.digitalocean.com/details#spam

**Comment by fpapon** [comment]
@Nek- not shure to understand because the PR seems to be good.

**Comment by Nek-** [comment]
@fpapon this PR is useless. As well as many other the guy did. Checkout its account and contributions of the last day.

**Comment by bdemers** [comment]
@Nek- I understand some folks are gaming the system, but as long as it's a valid fix, we will take it.
Now... if we had to PRs to handle, that's a different problem ;)

**Pull request merged**
