### PR TITLE
Add info about the SameSite cookie flag

### PR DESCRIPTION
**Pull request by boris-petrov**
Implementation of the flag is [here](https://github.com/apache/shiro/pull/67).

### CODE REVIEW

**Comment by colincasey** [comment]
@fpapon when is the expected release date of `1.5.0`?  there's nothing set on the [release page](https://issues.apache.org/jira/projects/SHIRO/versions/12344991) in Jira and those Chrome 80 changes around SameSite cookies are coming up fast 😄

**Comment by fpapon** [comment]
@colincasey 1.5.0 will be release before the end of this month ;)

**Comment by Ironcache** [comment]
Is the plan still to release this by the end of November?

**Comment by fpapon** [comment]
> Is the plan still to release this by the end of November?

The cut of the release is in progress, but it will be hard to release this by the end of Novembre ;)

**Comment by snsingla-82** [comment]
@fpapon  : Do you have any updates on when shall shiro 1.5.0 be released ? We want to pull it in as Chrome 80 changes are due in early February 2020.

**Comment by fpapon** [comment]
@snsingla-82 we have some issues with the release process but we try to fix it quickly

**Comment by snsingla-82** [comment]
@fpapon  : Thanks ! Do we have a tentative rough timeline? Or, when can we expect an update on the timeline?

**Comment by fpapon** [comment]
@snsingla-82 I'll do my best for next week

**Comment by fpapon** [comment]
@snsingla-82 the vote passed, I'm merging this.

**Pull request merged**
